# Generated by Django 6.1.1 on 2026-09-26 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0041_nia_security"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="niaauditlog",
            new_name="home_niaaud_user_id_17cc8a_idx",
            old_name="home_niaaudit_user_63c0df_idx",
        ),
        migrations.RenameIndex(
            model_name="niaauditlog",
            new_name="home_niaaud_role_18c1d8_idx",
            old_name="home_niaaudit_role_91b8cc_idx",
        ),
        migrations.RenameIndex(
            model_name="niacallerverification",
            new_name="home_niacal_phone_e_39e306_idx",
            old_name="home_niacall_phone_2e0c3b_idx",
        ),
    ]
