# Generated by Django 6.1.1 on 2026-09-27

from decimal import Decimal

from django.db import migrations, models


def seed_delivery_pay_profile(apps, schema_editor):
    DeliveryPayProfile = apps.get_model("home", "DeliveryPayProfile")
    DeliveryPayProfile.objects.get_or_create(
        name="Shopiva Standard Rider Pay",
        defaults={
            "base_per_delivery": Decimal("100.00"),
            "per_km_rate": Decimal("15.00"),
            "minimum_payout": Decimal("500.00"),
            "auto_payout_enabled": True,
            "auto_payout_threshold": Decimal("500.00"),
            "notes": "Default starting schedule: KSh 100 per verified delivery plus KSh 15 per recorded delivery kilometre. Review against approved Shopiva transport economics before production commercial changes.",
            "is_active": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0042_align_nia_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryPayProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
                ("base_per_delivery", models.DecimalField(decimal_places=2, default=Decimal("100.00"), max_digits=10)),
                ("per_km_rate", models.DecimalField(decimal_places=2, default=Decimal("15.00"), max_digits=10)),
                ("minimum_payout", models.DecimalField(decimal_places=2, default=Decimal("500.00"), max_digits=10)),
                ("auto_payout_enabled", models.BooleanField(default=True)),
                ("auto_payout_threshold", models.DecimalField(decimal_places=2, default=Decimal("500.00"), max_digits=10)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-is_active", "-updated_at"),
                "constraints": [
                    models.CheckConstraint(condition=models.Q(base_per_delivery__gte=0), name="deliverypay_base_gte_0"),
                    models.CheckConstraint(condition=models.Q(per_km_rate__gte=0), name="deliverypay_km_gte_0"),
                    models.CheckConstraint(condition=models.Q(minimum_payout__gt=0), name="deliverypay_min_payout_gt_0"),
                    models.CheckConstraint(condition=models.Q(auto_payout_threshold__gt=0), name="deliverypay_auto_threshold_gt_0"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeliveryWallet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payout_phone", models.CharField(blank=True, max_length=30)),
                ("available_balance", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("pending_payout_balance", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("total_earned", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("total_paid", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("auto_payout_enabled", models.BooleanField(default=True)),
                ("auto_payout_threshold", models.DecimalField(decimal_places=2, default=Decimal("500.00"), max_digits=10)),
                ("last_payout_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("agent", models.OneToOneField(on_delete=models.deletion.CASCADE, related_name="wallet", to="home.deliveryagent")),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(condition=models.Q(available_balance__gte=0), name="deliverywallet_available_gte_0"),
                    models.CheckConstraint(condition=models.Q(pending_payout_balance__gte=0), name="deliverywallet_pending_gte_0"),
                    models.CheckConstraint(condition=models.Q(total_earned__gte=0), name="deliverywallet_earned_gte_0"),
                    models.CheckConstraint(condition=models.Q(total_paid__gte=0), name="deliverywallet_paid_gte_0"),
                    models.CheckConstraint(condition=models.Q(auto_payout_threshold__gt=0), name="deliverywallet_auto_threshold_gt_0"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeliveryPayout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("phone", models.CharField(max_length=30)),
                ("status", models.CharField(choices=[("queued", "Queued"), ("processing", "Processing"), ("paid", "Paid"), ("failed", "Failed"), ("cancelled", "Cancelled")], default="queued", max_length=20)),
                ("trigger", models.CharField(choices=[("automatic", "Automatic"), ("manual", "Rider requested"), ("admin", "Admin")], default="automatic", max_length=20)),
                ("provider", models.CharField(default="mpesa_b2c", max_length=30)),
                ("provider_reference", models.CharField(blank=True, max_length=120)),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                ("idempotency_key", models.CharField(max_length=120, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("agent", models.ForeignKey(on_delete=models.deletion.PROTECT, related_name="payouts", to="home.deliveryagent")),
            ],
            options={
                "ordering": ("-created_at",),
                "constraints": [
                    models.CheckConstraint(condition=models.Q(amount__gt=0), name="deliverypayout_amount_gt_0"),
                ],
                "indexes": [
                    models.Index(fields=("agent", "status", "created_at"), name="home_delive_agent_i_9923fd_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeliveryEarning",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("distance_km", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                ("distance_source", models.CharField(default="estimated", max_length=30)),
                ("base_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("distance_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("status", models.CharField(choices=[("available", "Available"), ("reserved", "Reserved for payout"), ("paid", "Paid"), ("reversed", "Reversed")], default="available", max_length=20)),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                ("agent", models.ForeignKey(on_delete=models.deletion.PROTECT, related_name="earnings", to="home.deliveryagent")),
                ("order", models.OneToOneField(on_delete=models.deletion.CASCADE, related_name="delivery_earning", to="home.order")),
                ("pay_profile", models.ForeignKey(on_delete=models.deletion.PROTECT, related_name="earnings", to="home.deliverypayprofile")),
                ("payout", models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name="earnings", to="home.deliverypayout")),
            ],
            options={
                "ordering": ("-earned_at",),
                "constraints": [
                    models.CheckConstraint(condition=models.Q(distance_km__gte=0), name="deliveryearning_distance_gte_0"),
                    models.CheckConstraint(condition=models.Q(base_amount__gte=0), name="deliveryearning_base_gte_0"),
                    models.CheckConstraint(condition=models.Q(distance_amount__gte=0), name="deliveryearning_distance_amt_gte_0"),
                    models.CheckConstraint(condition=models.Q(total_amount__gt=0), name="deliveryearning_total_gt_0"),
                ],
                "indexes": [
                    models.Index(fields=("agent", "status", "earned_at"), name="home_delive_agent_i_51f3ad_idx"),
                ],
            },
        ),
        migrations.RunPython(seed_delivery_pay_profile, migrations.RunPython.noop),
    ]
