# Generated by Django 6.1.1 on 2026-09-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0043_delivery_staff_payouts"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="business_nature",
            field=models.CharField(
                blank=True,
                help_text="What products or services does the business sell or provide?",
                max_length=500,
            ),
        ),
    ]
