# Generated by Django 6.1.1 on 2026-10-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0047_staff_payments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffpayment",
            name="idempotency_key",
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
