# Generated by Django 6.1.1 on 2026-10-01
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ("home", "0048_alter_staffpayment_idempotency_key"),
    ]
    operations = [
        migrations.AlterField(
            model_name="niacallerverification",
            name="pin_code",
            field=models.CharField(max_length=128),
        ),
    ]
